gret_notes/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path(r'^summernote/', include('django_summernote.urls')),
    path('tags/', include('tags.urls'), name='tags'),
    path('signup/', views.signup, name='signup'),
    path('auth/', include('django.contrib.auth.urls'), name='auth'),
    path('notes/', include('notes.urls'), name='notes'),
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
]

notes/urls.py
from django.urls import path

from . import views


app_name = 'notes'
urlpatterns = [
    path('', views.index, name='index'),
    path('tagged/', views.index, name='tagged'),
    path('new/', views.new, name='new'),
    path('<int:note_id>/edit/', views.edit, name='edit'),
    path('<int:note_id>/del/', views.delete, name='delete'),
]

tags/urls.py
from django.urls import path

from . import views


app_name = 'tags'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:tag_id>/edit/', views.edit, name='edit'),
    path('<int:tag_id>/del/', views.delete, name='delete'),
]

tags/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from taggit.models import TagBase, GenericTaggedItemBase


class GuardedTag(TagBase):
    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")


class TaggedWhatever(GenericTaggedItemBase):
    tag = models.ForeignKey(
        GuardedTag,
        on_delete=models.CASCADE,
        related_name="%(app_label)s_%(class)s_items",
    )

tags/forms.py
from django.forms import ModelForm, TextInput

from taggit.models import Tag


class TagForm(ModelForm):
    class Meta:
        model = Tag
        fields = ['name']
        widgets = {
            'name': TextInput(attrs={'size': 24})
        }

tags/views.py
from django.contrib import messages
from django.contrib.messages import add_message
from django.shortcuts import get_object_or_404, redirect, render

from guardian.decorators import permission_required_or_403
from guardian.shortcuts import assign_perm, remove_perm, get_objects_for_user

from notes.models import Note

from tags.models import GuardedTag
from taggit.utils import parse_tags

from .forms import TagForm


def index(request):
    """
    List of used tags. Filtering by tags options included (tbd).
    :param request: HTTP request.
    """

    context = {
        'tags': get_objects_for_user(request.user, 'tags.view_guardedtag').order_by('name'),
    }
    return render(request, 'tags/index.html', context)


@permission_required_or_403('tags.view_guardedtag', (GuardedTag, 'id', 'tag_id'))
def edit(request, tag_id):
    """
    POST: Edit form for selected tag.
    GET: Display tag form populated with tag's data.
    If changing tag's name, tries to make new tag, gives view perm, and reassigns all notes of that user to it.
    :param tag_id: Selected tag's ID.
    :param request: HTTP request.

    """

    old_tag = get_object_or_404(GuardedTag, pk=tag_id)
    new_tag = GuardedTag()
    tag_list = []

    # POST method - edit existing tag
    if request.method == 'POST':
        form = TagForm(request.POST, instance=new_tag)
        # if form is valid, parse string into tag names
        if form.is_valid():
            tag_words = parse_tags(form.instance.name)
            # in case of more than one name - make a list of tags, otherwise search for one tag or create one
            if len(tag_words) > 1:
                for word in tag_words:
                    tag = GuardedTag.objects.filter(name=word).first()
                    if not tag:
                        tag = GuardedTag(name=word, slug=word)
                        tag.save()
                    tag_list.append(tag)
            else:
                new_tag = GuardedTag.objects.filter(name=tag_words[0]).first()
                if new_tag is None:
                    form.save()

        elif 'Tag with this Name already exists.' in form.errors['name']:
            new_tag = GuardedTag.objects.filter(name=form.instance.name).first()
            # if there is no change provided - just redirect to index
            if new_tag:
                if old_tag.name == new_tag.name:
                    add_message(request, messages.INFO, 'There was no change provided to edited tag.')
                    return redirect('tags:index')
        else:
            new_tag = None

        # deletes permission for the old tag and gives to the new one
        if new_tag is not None or len(tag_list) >= 1:
            if not tag_list:
                tag_list.append(new_tag)
            remove_perm('view_guardedtag', request.user, old_tag)
            # check for notes with the old tag and replace it with the new one
            notes = Note.objects.filter(creator=request.user, tags__name__in=[old_tag.name]).distinct()
            # for safety reason - exclude notes without change perm (even though creator should always has it)
            notes = get_objects_for_user(request.user, 'notes.change_note', klass=notes)
            if notes:
                for note in notes:
                    note.tags.remove(old_tag)
                    for tag in tag_list:
                        assign_perm('view_guardedtag', request.user, tag)
                        note.tags.add(tag)
                add_message(request, messages.INFO, 'Tag changed and replaced in note(s).')
                return redirect('tags:index')

            add_message(request, messages.INFO, 'Tag changed.')
        return redirect('tags:index')

    # GET method - display and populate form with note data
    context = {
        'tags': get_objects_for_user(request.user, 'tags.view_guardedtag').order_by('name'),
        'form': TagForm(initial={
            'name': old_tag.name,
        }),
        'edit_tag_id': tag_id,
    }
    return render(request, 'tags/index.html', context)


@permission_required_or_403('tags.view_guardedtag', (GuardedTag, 'id', 'tag_id'))
def delete(request, tag_id):
    """
    Delete selected tag - gives away view permission, deletes from user's notes,
    and erases tag from DB if no one is using it.
    :param tag_id: Selected tag's ID.
    :param request: HTTP request.
    """

    tag = get_object_or_404(GuardedTag, pk=tag_id)
    notes = Note.objects.filter(creator=request.user, tags__name__in=[tag.name]).distinct()
    for note in notes:
        note.tags.remove(tag)
    remove_perm('view_guardedtag', request.user, tag)
    if notes:
        add_message(request, messages.INFO, 'Tag removed from note(s).')

    # if no one is using this tag - clear db from it
    if not Note.objects.filter(tags__name__in=[tag.name]).all():
        GuardedTag.objects.get(pk=tag_id).delete()

    return redirect('tags:index')

tags/templates/tags/index.html
{% extends 'base.html' %}

{% block content %}
{% load guardian_tags %}

    <h2>Tags</h2>

    {% if tags %}

        {% load crispy_forms_tags %}

        {% if not edit_tag_id %}
            <form action="{% url 'notes:index' %}" method="post" novalidate>
                <div class="form-check">
            {% csrf_token %}
        {% endif %}
        {% for tag in tags %}
        {% get_obj_perms request.user for tag as "tag_perms" %}
            <div class="card bg-transparent">
                <div class="card-body my-n3 pl-4 pr-3">
                    {% if not edit_tag_id %}
                        <input class="form-check-input" type="checkbox" name="tags" value="{{ tag.name }}">
                    {% endif %}

                    {% if edit_tag_id != tag.id %}
                        {% with tags=tag.name %}
                            <a href="{% url 'notes:tagged' %}?tags={{ tags }}"><strong>{{ tag.name|safe }}</strong></a>
                        {% endwith %}

                        <!-- Delete feature section -->
                        {% if 'view_guardedtag' in tag_perms %}
                            <!-- Button trigger modal -->
                            <button type="button" class="btn btn-danger float-right ml-1 mr-n2 btn-sm" data-toggle="modal" data-target="#tag_{{ tag.id }}">
                                Delete
                            </button>
                            <!-- Modal -->
                            <div class="modal fade" id="tag_{{ tag.id }}" tabindex="-1" role="dialog" aria-labelledby="tag_{{ tag.id }}_Label" aria-hidden="true">
                                  <div class="modal-dialog">
                                        <div class="modal-content">
                                              <div class="modal-header">
                                                  <h5 class="modal-title" id="tag_{{ tag.id }}_Label">Confirm deleting tag:</h5>
                                                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                      <span aria-hidden="true">&times;</span>
                                                  </button>
                                              </div>
                                              <div class="modal-body">
                                                  <p>{{ tag.name|safe }}</p>
                                              </div>
                                              <div class="modal-footer">
                                                    <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                                                    <a class="btn btn-danger" href="{% url 'tags:delete' tag.id %}">Confirm</a>
                                              </div>
                                        </div>
                                  </div>
                            </div>
                        {% else %}
                            <span class="btn btn-outline-danger disabled float-right ml-1 mr-n2 btn-sm">Delete</span>
                        {% endif %}
                        <!-- Edit feature section -->
                        {% if 'view_guardedtag' in tag_perms %}
                            <a class="btn btn-success float-right mx-1 btn-sm" href="{% url 'tags:edit' tag.id %}">Edit</a>
                        {% else %}
                            <span class="btn btn-outline-success disabled float-right mx-1 btn-sm">Edit</span>
                        {% endif %}
                    {% else %}
                        <form action="{% url 'tags:edit' tag.id %}" method="post">
                            {% csrf_token %}

                            {{ form.non_field_errors }}

                            <div class="d-flex my-n3">
                                <div class="p-2 flex-grow-1 mt-3">
                                    {{ form|crispy }}
                                </div>
                                <div class="p-2 mt-5">
                                    <input type="submit" value="Submit" class="btn btn-primary">
                                </div>
                            </div>
                        </form>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        {% if not edit_tag_id %}
                <br><input type="Submit" value="Look for notes with any of selected tags" class="btn btn-primary">
                </div>
            </form>
        {% endif %}
    {% else %}
        <p>No tags to display.</p>
    {% endif %}

	<script type="text/javascript" >
		function show_hide(show_id, hide_id){
			document.getElementById(show_id).style.display = 'inline';
			document.getElementById(hide_id).style.display = 'none';
        }
	</script>
{% endblock %}