gret_notes/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path(r'^summernote/', include('django_summernote.urls')),
    path('tags/', include('tags.urls'), name='tags'),
    path('signup/', views.signup, name='signup'),
    path('auth/', include('django.contrib.auth.urls'), name='auth'),
    path('notes/', include('notes.urls'), name='notes'),
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
]

notes/urls.py
from django.urls import path

from . import views


app_name = 'notes'
urlpatterns = [
    path('', views.index, name='index'),
    path('tagged/', views.index, name='tagged'),
    path('new/', views.new, name='new'),
    path('<int:note_id>/edit/', views.edit, name='edit'),
    path('<int:note_id>/del/', views.delete, name='delete'),
]

tags/urls.py
from django.urls import path

from . import views


app_name = 'tags'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:tag_id>/edit/', views.edit, name='edit'),
    path('<int:tag_id>/del/', views.delete, name='delete'),
]

notes/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from taggit.managers import TaggableManager

from tags.models import TaggedWhatever


class Note(models.Model):
    title = models.CharField(max_length=128)
    body = models.CharField(max_length=20480, blank=True)
    created_at = models.DateTimeField('date created', default=datetime.datetime.now(tz=timezone.utc))
    updated_at = models.DateTimeField('date updated', default=datetime.datetime.now(tz=timezone.utc))
    creator = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    tags = TaggableManager(through=TaggedWhatever, blank=True)

    def __str__(self):
        return self.title

notes/forms.py
from .models import Note

from django.forms import ModelForm, TextInput
from django_summernote.widgets import SummernoteWidget


class NoteForm(ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'body', 'tags']
        widgets = {
            'title': TextInput(attrs={'size': 128}),
            'body':  SummernoteWidget(attrs={
                'summernote': {
                    'toolbar': [
                        ['style', ['bold', 'italic', 'underline', 'clear']],
                        ['font', ['strikethrough', 'superscript', 'subscript', 'hr']],
                        ['fontname', ['fontname']],
                        ['color', ['color']],
                        ['para', ['ul', 'ol', 'paragraph']],
                        ['insert', ['link', 'picture']],
                    ],
                }
            }),
            'tags': TextInput(attrs={'size': 128}),
        }

notes/views.py
import datetime

from django.contrib import messages
from django.contrib.messages import add_message
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse

from guardian.decorators import permission_required_or_403
from guardian.shortcuts import assign_perm, get_objects_for_user

from urllib.parse import urlencode

from .forms import NoteForm
from .models import Note


def index(request):
    """
    List of user's notes with links to permitted actions.
    Expanded with option to filter notes with list of tags.
    :GET/POST param tags: list of tag's names to filter with.
    :param request: HTTP request.
    """

    notes = get_objects_for_user(request.user, 'notes.view_note')

    # POST method - from tags index's filter form
    if request.method == 'POST':
        tags = request.POST.getlist('tags')
        if tags:
            # convert tags into query string (doseq = True! as tags is a list)
            return redirect(reverse('notes:tagged') + '?' + urlencode({'tags': tags}, doseq=True))
        else:
            # with empty form - display notes with no Tags at all
            return render(request, 'notes/index.html', context={
                'notes': notes.filter(tags__exact=None).order_by('-updated_at')
            })
    # GET method - look for tags in notes and display them
    else:
        tags = request.GET.getlist('tags')
        if tags:
            filtered_notes = notes.filter(tags__name__in=tags)
            return render(request, 'notes/index.html', context={'notes': filtered_notes.order_by('-updated_at'), })
        # with no tags in GET req, display all notes with view perm
        else:
            return render(request, 'notes/index.html', context={'notes': notes.order_by('-updated_at'), })


def new(request):
    """
    POST: Create new note for currently logged in user, and give it permissions.
    GET: Display empty note form.
    :param request: HTTP request.
    """

    # POST method - create new note
    if request.method == 'POST':
        form = NoteForm(request.POST)

        if form.is_valid():
            note = form.save(commit=False)
            note.creator = request.user
            note.created_at = datetime.datetime.utcnow()
            note.updated_at = datetime.datetime.utcnow()
            note.save()
            # save m2m for taggit's tags
            form.save_m2m()
            # assign all rights to the creator
            assign_perm('view_note', request.user, note)
            assign_perm('change_note', request.user, note)
            assign_perm('delete_note', request.user, note)
            # assign view rights for all the tags used
            for tag in note.tags.all():
                assign_perm('view_guardedtag', request.user, tag)
            add_message(request, messages.INFO, 'Note created succesfuly.')
            return redirect('notes:index')
        else:
            add_message(request, messages.INFO, 'Something gone wrong!')
            return redirect('notes:index')
    # GET method - display clean form
    else:
        return render(request, 'notes/new.html', {'form': NoteForm()})


@permission_required_or_403('notes.change_note', (Note, 'id', 'note_id'))
def edit(request, note_id):
    """
    POST: Edit form for selected note.
    GET: Display note form populated with note's data.
    :param request: HTTP request.
    :param note_id: Selected note's ID.
    """

    note = get_object_or_404(Note, pk=note_id)

    # POST method - edit existing note
    if request.method == 'POST':
        form = NoteForm(request.POST, instance=note)
        if form.is_valid():
            form.save(commit=False)
            note.updated_at = datetime.datetime.utcnow()
            note.save()
            # save m2m for taggit's tags
            form.save_m2m()
            # assign view rights for all the tags used
            for tag in note.tags.all():
                assign_perm('view_guardedtag', request.user, tag)
            add_message(request, messages.INFO, 'Note edited succesfuly.')
            return redirect('notes:index')
        else:
            add_message(request, messages.INFO, 'Something gone wrong!')
            return redirect('notes:index')
    # GET method - populate form with note data
    else:
        context = {
            'note': note,
            # pre-populate note's form when editing
            'form': NoteForm(initial={
                'title': note.title,
                'body': note.body,
                'tags': ' '.join(list(note.tags.names())),
            }),
        }
        return render(request, 'notes/edit.html', context)


@permission_required_or_403('notes.delete_note', (Note, 'id', 'note_id'))
def delete(request, note_id):
    """
    Delete selected note.
    :param request: HTTP request.
    :param note_id: Selected note's ID.
    """

    note = get_object_or_404(Note, pk=note_id)
    if note:
        # not sure if clear is necessary, left just in case
        note.tags.clear()
        note.delete()
        add_message(request, messages.INFO, 'Note deleted succesfuly.')
    return redirect('notes:index')

notes/templates/notes/_noteForm.html
{% load crispy_forms_tags %}

<form action="{{ url_address }}" method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}

    {{ form|crispy|safe }}

    <input type="Submit" value="Submit" class="btn btn-primary">
</form>
<script>
    $(document).ready(function() {
        $('#summernote').summernote();
    });
</script>

notes/templates/notes/edit.html
{% extends 'base.html' %}

{% block content %}
<h2>Edit note: {{ note.title }}</h2>
{% with url_address as url('notes:edit') %}
    {% include 'notes/_noteForm.html' %}
{% endwith %}

{% endblock %}

notes/templates/notes/index.html
{% extends 'base.html' %}

{% block content %}
{% load guardian_tags %}
    {% if notes %}
        <div>
            {% for note in notes %}
            {% get_obj_perms request.user for note as "note_perms" %}
                <div class="card border-dark my-2">
                    <div class="card-header bg-light border-dark d-flex p-2">
                        <div class="p-2 flex-grow-1">
                            <span class="btn btn-outline-link disabled text-left ml-n2 text-black">
                                <h5>{{ note.title|safe }}</h5>
                            </span>
                        </div>
                        <div class="p-2">
                            <div class="mx-2" style="width: 130px;">
                            <!-- Delete feature section -->
                            {% if 'delete_note' in note_perms %}
                                <!-- Button trigger modal -->
                                <button type="button" class="btn btn-danger float-right ml-1 mr-n2" data-toggle="modal" data-target="#note_{{ note.id }}">
                                    Delete
                                </button>
                                <!-- Modal -->
                                <div class="modal fade" id="note_{{ note.id }}" tabindex="-1" role="dialog" aria-labelledby="note_{{ note.id }}_Label" aria-hidden="true">
                                      <div class="modal-dialog">
                                            <div class="modal-content">
                                                  <div class="modal-header">
                                                      <h5 class="modal-title" id="note_{{ note.id }}_Label">Confirm deleting note:</h5>
                                                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                          <span aria-hidden="true">&times;</span>
                                                      </button>
                                                  </div>
                                                  <div class="modal-body">
                                                      <p>{{ note.title|safe }}</p>
                                                  </div>
                                                  <div class="modal-footer">
                                                        <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                                                        <a class="btn btn-danger" href="{% url 'notes:delete' note.id %}">Confirm</a>
                                                  </div>
                                            </div>
                                      </div>
                                </div>
                            {% else %}
                                <span class="btn btn-outline-danger disabled float-right ml-1 mr-n2">Delete</span>
                            {% endif %}
                            <!-- Edit feature section -->
                            {% if 'change_note' in note_perms %}
                                <a class="btn btn-success float-right mx-1" href="{% url 'notes:edit' note.id %}">Edit</a>
                            {% else %}
                                <span class="btn btn-outline-success disabled float-right mx-1">Edit</span>
                            {% endif %}
                            </div>
                        </div>
                    </div>

                    <div class="card-body text-dark">
                        <p class="card-text">
                        {{ note.body|safe }}
                        {% if note.tags.all %}
                            <hr><b>Tags:</b> {{ note.tags.names|join:", " }}
                        {% endif %}
                        </p>
                    </div>

                    <div class="card-footer bg-transparent border-dark mb-1">
                        <p class="my-n1 mx-n1">Last update at {{ note.updated_at }} || Created at {{ note.created_at }} by {{ note.creator|safe }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No notes to display.</p>
    {% endif %}

	<script type="text/javascript" >
		function show_hide(show_id, hide_id){
			document.getElementById(show_id).style.display = 'inline';
			document.getElementById(hide_id).style.display = 'none';
        }
	</script>
{% endblock %}

notes/templates/notes/new.html
{% extends 'base.html' %}

{% block content %}

<h2>New note</h2>
{% with url_address as url('notes:new') %}
    {% include 'notes/_noteForm.html' %}
{% endwith %}

{% endblock %}