gret_notes/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path(r'^summernote/', include('django_summernote.urls')),
    path('tags/', include('tags.urls'), name='tags'),
    path('signup/', views.signup, name='signup'),
    path('auth/', include('django.contrib.auth.urls'), name='auth'),
    path('notes/', include('notes.urls'), name='notes'),
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
]

notes/urls.py
from django.urls import path

from . import views


app_name = 'notes'
urlpatterns = [
    path('', views.index, name='index'),
    path('tagged/', views.index, name='tagged'),
    path('new/', views.new, name='new'),
    path('<int:note_id>/edit/', views.edit, name='edit'),
    path('<int:note_id>/del/', views.delete, name='delete'),
]

tags/urls.py
from django.urls import path

from . import views


app_name = 'tags'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:tag_id>/edit/', views.edit, name='edit'),
    path('<int:tag_id>/del/', views.delete, name='delete'),
]

gret_notes/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render


def home(request):

    return render(request, 'home.html')


def signup(request):

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('/notes/')

    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

gret_notes/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>gret_notes - personal noting app</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

        <!-- include summernote css/js -->
        <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    </head>

    <body class="bg-dark">
        <div class="container py-2 bg-dark">
            <div class="jumbotron text-center py-5 my-1">
                <h1>Gret Notes</h1>
            </div>

            <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <div class="collapse navbar-collapse">
                    <div class="navbar-nav mb-1 mr-auto">
                        <a class="nav-item nav-link active" href="/">Home</a>
                        {% if user.is_authenticated %}
                            <a class="nav-item nav-link" href="{% url 'notes:index' %}">Notes</a>
                            <a class="nav-item nav-link" href="{% url 'notes:new' %}">New note</a>
                            <a class="nav-item nav-link" href="{% url 'tags:index' %}">Tags</a>
                        {% endif %}
                    </div>
                    <div class="navbar-nav mr-right">
                    {% if user.is_authenticated %}
                        <span class="nav-item nav-link text-success">
                            <span>Logged in user:</span>
                            <span><strong>{{ user|safe }}</strong></span>
                        </span>
                        <a class="nav-item nav-link text-danger active" href="/auth/logout">Logout</a>
                    {% else %}
                        <a class="nav-item nav-link" href="/auth/login">LogIn</a>
                    {% endif %}
                    </div>
                </div>
            </nav>

            {% if messages %}
            <div class="alert alert-primary" role="alert">
                {% for msg in messages %}
                    {{msg.message}}<br>
                {% endfor %}
            </div>
            {% endif %}

            <div class="jumbotron py-3">
                    {% block content %}{% endblock %}
            </div>

            <div class="jumbotron text-center py-3 my-1">
                <h6>TBD</h6>
            </div>
        </div>
    </body>
</html>

gret_notes/templates/home.html
{% extends "base.html" %}

{% block content %}

<h3>Home Page</h3><hr>
<h4>Basic information:</h4><br>
<p>Owner: Piotr Gretkierewicz</p>
<p><a href="https://www.linkedin.com/in/piotr-gretkierewicz-6241a114a/">LinkedIn</a></p>
<p><a href="https://github.com/gretkierewicz/gret_notes">Github</a></p>

{% endblock %}